#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CHARSET = ROOT / "assets" / "charsets" / "level-1-3500.txt"
DEFAULT_SUBSET = ROOT / "assets" / "charsets" / "common-zh-3000.txt"
DEFAULT_OUT = ROOT / "src" / "fonts" / "ZhSubsetFontData.cpp"
DEFAULT_FONT_CANDIDATES = (
    Path(r"C:\Windows\Fonts\msyh.ttc"),
    Path(r"C:\Windows\Fonts\Deng.ttf"),
    Path(r"C:\Windows\Fonts\simhei.ttf"),
    Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
    Path("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc"),
)


def load_charset(path: Path, count: int) -> list[str]:
    text = path.read_text(encoding="utf-8")
    chars: list[str] = []
    seen: set[str] = set()
    for ch in text:
        if "\u4e00" <= ch <= "\u9fff" and ch not in seen:
            chars.append(ch)
            seen.add(ch)
        if len(chars) >= count:
            break
    if len(chars) < count:
        raise SystemExit(f"only found {len(chars)} Han chars in {path}, need {count}")
    return chars


def detect_default_font() -> Path:
    for candidate in DEFAULT_FONT_CANDIDATES:
        if candidate.exists():
            return candidate
    raise SystemExit("no default CJK font found; pass --font explicitly")


def pack_4bpp(canvas: Image.Image, px: int) -> bytes:
    packed = bytearray()
    for yy in range(px):
        row = [canvas.getpixel((xx, yy)) for xx in range(px)]
        for start in range(0, px, 2):
            byte = 0
            for offset, value in enumerate(row[start:start + 2]):
                level = min(15, (value * 16) // 256)
                shift = (1 - offset) * 4
                byte |= (level & 0x0F) << shift
            packed.append(byte)
    return bytes(packed)


def render_glyph(font_path: Path, glyph: str, px: int) -> tuple[bytes, tuple[int, int, int, int]]:
    # Use a slightly smaller point size so the glyph stays inside the target box.
    point_size = max(8, int(round(px * 0.90)))
    font = ImageFont.truetype(str(font_path), point_size, index=0)
    canvas = Image.new("L", (px, px), 0)
    draw = ImageDraw.Draw(canvas)
    bbox = draw.textbbox((0, 0), glyph, font=font)
    width = bbox[2] - bbox[0]
    height = bbox[3] - bbox[1]
    x = (px - width) // 2 - bbox[0]
    y = (px - height) // 2 - bbox[1]
    draw.text((x, y), glyph, fill=255, font=font)
    glyph_bbox = canvas.getbbox() or (0, 0, 0, 0)
    return pack_4bpp(canvas, px), glyph_bbox


def union_box(boxes: list[tuple[int, int, int, int]]) -> tuple[int, int, int, int]:
    valid = [box for box in boxes if box[2] > box[0] and box[3] > box[1]]
    if not valid:
        return (0, 0, 0, 0)
    left = min(box[0] for box in valid)
    top = min(box[1] for box in valid)
    right = max(box[2] for box in valid)
    bottom = max(box[3] for box in valid)
    return left, top, right - left, bottom - top


def format_bytes(values: bytes, width: int = 16) -> Iterable[str]:
    for start in range(0, len(values), width):
        chunk = values[start:start + width]
        yield ", ".join(f"0x{value:02X}" for value in chunk)


def write_cpp(
    out_path: Path,
    font_path: Path,
    chars: list[str],
    data16: list[bytes],
    data24: list[bytes],
    box16: tuple[int, int, int, int],
    box24: tuple[int, int, int, int],
) -> None:
    indexed = sorted(
        ((ord(ch), ch, glyph16, glyph24) for ch, glyph16, glyph24 in zip(chars, data16, data24)),
        key=lambda item: item[0],
    )
    codepoints = [item[0] for item in indexed]
    sorted16 = [item[2] for item in indexed]
    sorted24 = [item[3] for item in indexed]

    lines: list[str] = []
    lines.append("// Auto-generated by tools/fonts/generate_zh_subset_font.py")
    lines.append(f"// Source font: {font_path}")
    lines.append('#include "fonts/ZhSubsetFont.h"')
    lines.append("")
    lines.append("namespace fonts {")
    lines.append("")
    lines.append(f"const uint16_t kZhCommon3000Codepoints[{len(codepoints)}] = {{")
    cp_lines = []
    for start in range(0, len(codepoints), 16):
        chunk = codepoints[start:start + 16]
        cp_lines.append("  " + ", ".join(f"0x{cp:04X}" for cp in chunk) + ",")
    lines.extend(cp_lines)
    lines.append("};")
    lines.append("")
    lines.append(f"const uint8_t kZhFont16BoxLeft = {box16[0]};")
    lines.append(f"const uint8_t kZhFont16BoxTop = {box16[1]};")
    lines.append(f"const uint8_t kZhFont16BoxWidth = {box16[2]};")
    lines.append(f"const uint8_t kZhFont16BoxHeight = {box16[3]};")
    lines.append(f"const uint8_t kZhFont24BoxLeft = {box24[0]};")
    lines.append(f"const uint8_t kZhFont24BoxTop = {box24[1]};")
    lines.append(f"const uint8_t kZhFont24BoxWidth = {box24[2]};")
    lines.append(f"const uint8_t kZhFont24BoxHeight = {box24[3]};")
    lines.append("")

    lines.append(
        f"const uint8_t kZhCommon3000Px16[{len(sorted16) * len(sorted16[0])}] = {{"
    )
    flat16 = b"".join(sorted16)
    for line in format_bytes(flat16):
        lines.append("  " + line + ",")
    lines.append("};")
    lines.append("")

    lines.append(
        f"const uint8_t kZhCommon3000Px24[{len(sorted24) * len(sorted24[0])}] = {{"
    )
    flat24 = b"".join(sorted24)
    for line in format_bytes(flat24):
        lines.append("  " + line + ",")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace fonts")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--charset", type=Path, default=DEFAULT_CHARSET)
    parser.add_argument("--subset-out", type=Path, default=DEFAULT_SUBSET)
    parser.add_argument("--font", type=Path, default=detect_default_font())
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--count", type=int, default=3000)
    args = parser.parse_args()

    chars = load_charset(args.charset, args.count)
    args.subset_out.write_text("".join(chars), encoding="utf-8")
    rendered16 = [render_glyph(args.font, ch, 16) for ch in chars]
    rendered24 = [render_glyph(args.font, ch, 24) for ch in chars]
    data16 = [item[0] for item in rendered16]
    data24 = [item[0] for item in rendered24]
    box16 = union_box([item[1] for item in rendered16])
    box24 = union_box([item[1] for item in rendered24])
    write_cpp(args.out, args.font, chars, data16, data24, box16, box24)
    print(f"generated {len(chars)} glyphs -> {args.out}")


if __name__ == "__main__":
    main()
