[platformio]
src_dir = .
include_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
  +<*>
  -<_tmp_partial_2037_real/>
  -<_tmp_partial_zip/>
  -<_tmp_xandronak_gdep073e01/>
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
